name: Pelican to Github Pages

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

backend:
  name: netlify-api
  url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: MarketingProInsider/marketingproinsider
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'true'
    - uses: rehanhaider/pelican-to-github-pages@v1.3.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}