name: Deploy changes to live/server

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your.server.com >> ~/.ssh/known_hosts

    - name: Deploy pelican application
      run: |
        ssh secrets.SSH_IP@secrets.SSH_USER << 'EOF'
        # Navigate to the deployment directory
        cd /home/marketingproinsider

        # Pull the latest changes
        git pull origin main

        # Build application
        make html
        EOF
