name: Deploy changes to live/server

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts

    # Step 3: Deploy Pelican Application
    - name: Deploy Pelican Application
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} << 'EOF'
        # Navigate to the deployment directory
        cd /home/marketingproinsider

        # Pull the latest changes
        sudo git pull origin master

        # Build application
        sudo make html
        EOF
